### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by go-spider** [YYRise/black-hat-go#1]
还剩4章

**Comment by 12end** [comment]
@YYRise 请问是在哪里看的blackhat-go，orelly的电子书嘛？找了好久pdf找不到，又不想单为这本书开个acm会员（现在130一年Orz

**Comment by evilAdan0s** [comment]
> @YYRise 请问是在哪里看的blackhat-go，orelly的电子书嘛？找了好久pdf找不到，又不想单为这本书开个acm会员（现在130一年Orz

我有这本的pdf

**Comment by 12end** [comment]
> > @YYRise 请问是在哪里看的blackhat-go，orelly的电子书嘛？找了好久pdf找不到，又不想单为这本书开个acm会员（现在130一年Orz
> 
> 我有这本的pdf

可否麻烦师傅发一份？1747433021@qq.com，万分感谢🙏

**Comment by go-spider** [comment]
@12end https://salttiger.com/archives/

**Comment by YYRise** [comment]
> 还剩4章

之前忙别的放下了，尽快把剩下的都翻译完成。欢迎多多提问题和建议！！

**Comment by YYRise** [comment]
终于完成了！！！
